--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/VennDev/VPlaceHolder
build-by-default: true
branches:
- main
projects:
  VPlaceHolder:
    path: ""
    model: virion
    type: library
...
